[tool.pylint.messages_control]
disable= [
        "missing-function-docstring",
        "missing-class-docstring",
        "missing-module-docstring",
        "pointless-string-statement",
        "redefined-outer-name"
]

[tool.pylint.MASTER]
ignore-paths = '^Monitoring/.ipynb_checkpoints/.*$'

[tool.black]
line-length = 83
target-version = ["py38", "py39", "py310", "py311"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.isort]
multi_line_output = 3
length_sort = true
